version: '3.8'

services:
  # Development-specific PostgreSQL configuration
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: danniwang
      POSTGRES_PASSWORD: MaxJax2023
      POSTGRES_DB: 2dots1line_dev

  # Development-specific Neo4j configuration
  neo4j:
    environment:
      NEO4J_AUTH: neo4j/devpassword
      NEO4J_dbms_logs_debug_enabled: "true"
    ports:
      - "7474:7474"
      - "7687:7687"

  # Development-specific Weaviate configuration
  weaviate:
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: text2vec-contextionary
      DEFAULT_VECTORIZER_MODULE: text2vec-contextionary
      LOG_LEVEL: debug
    ports:
      - "8080:8080"

  # Development-specific Redis configuration
  redis:
    command: redis-server --appendonly yes --requirepass devpassword
    ports:
      - "6379:6379"

  # Redis Commander for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: 2dots1line_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379:0:devpassword
    ports:
      - "8081:8081"
    depends_on:
      - redis

  # pgAdmin for development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: 2dots1line_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@2dots1line.com
      PGADMIN_DEFAULT_PASSWORD: devpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres 